# Generated by Django 3.2 on 2021-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracni_znacka', models.CharField(max_length=10)),
                ('znacka_a_typ', models.CharField(max_length=100)),
                ('pocet_km', models.IntegerField()),
                ('datum_TK', models.DateField()),
            ],
        ),
    ]
