# Generated by Django 3.2 on 2021-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_rename_auto_seznam'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='program',
            field=models.CharField(choices=[('B', 'Běžný zákazník'), ('Z', 'Zlatý program'), ('P', 'Platinový program')], max_length=1, null=True),
        ),
    ]
