# Generated by Django 3.2 on 2021-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_zakaznik_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='vypujcka',
            name='schvaleni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vypujcka',
            name='cena',
            field=models.IntegerField(null=True),
        ),
    ]
